theme: jekyll-theme-hemingway
title: William Olson
description: Natural Resource Conservation - University of Florida
navigation:
  - title: Work Experience
    url: "#work_experience"
  - title: Education
    url: "education"
  - title: Projects
    url: "projects"
  - title: Leadership
    url: "leadership"
  - title: Awards
    url: "awards"
